apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodtruck-discoveryapp
  labels:
    app: discoveryapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discoveryapp
  template:
    metadata:
      labels:
        app: discoveryapp
    spec:
      containers:
      - name: discoveryapp
        image: 588328284151.dkr.ecr.us-east-2.amazonaws.com/my-repository:latest
        ports:
        - containerPort: 5001
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5001
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
      imagePullSecrets:
        - name: ecr-registry-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
