apiVersion: v1
kind: Service
metadata:
  name: discoveryapp-service
spec:
  selector:
    app: discoveryapp
  ports:
  - name: discoveryapp-port
    protocol: TCP
    port: 80
    targetPort: 5001
  type: LoadBalancer