apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodtruck-discoveryapp
  labels:
    app: discoveryapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discoveryapp
  template:
    metadata:
      labels:
        app: discoveryapp
    spec:
      containers:
      - name: discoveryapp
        image: herabakirova/app:3.0
        ports:
        - containerPort: 5001
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: aws_secret_access_key
