apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
data:
  aws_access_key_id: QUtJQVlSNllaRjczUU1CQzNSM0U=
  aws_secret_access_key: dW5yOEU5TzZqQ0w5cWIrR1lUZHFRRFRmd0k2cVJMMk1yQStIMU5idw==
