apiVersion: v1
kind: Service
metadata:
  name: discoveryapp-service
spec:
  selector:
    app: discoveryapp
  ports:
  - name: discoveryapp-port
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
